.TH gnonograms 6 "June 30, 2011"
.SH NAME
\fBgnonograms\fP \- GTK program to design and solve Nonogram puzzles
.SH SYNOPSIS
.B gnonograms
.RI  " files" ...
.br
.B bar
.SH DESCRIPTION
This manual page documents briefly the
.B gnonograms
program
.PP
\fBgnonograms\fP is a GUI program that generates and solves Nonogram puzzles as well as allowing the user to design and save their own puzzles.  It is not intended for command line use and has no command line options other than the name of a single puzzle file to load on start up. 
.SH OPTIONS
\fB filename ... \fR
Specifies the name of the puzzle file to open on start up.  If not specified the program will start up in design mode with a blank puzzle.  
.SH AUTHOR
gnonograms was written by Jeremy Wootten <jeremywootten@gmail.com>
.PP
This manual page was written by Jeremy Wootten <jeremywootten@gmail.com>,
for the Debian project (and may be used by others).
